### ISSUE TITLE
Mutation: Refetch Queries appears to broadcast twice?

### ISSUE THREAD

**Issue by richisarch** [D-James-GH/cached_query#23]
Hi,

Great package! Really appreciate your work on this.

I am trying to create an optimistic update within a BLoC (flutter_bloc). Here is what I am doing.

1. I emit the new state within the bloc to optimistically update the UI.

```
emit(
        state.copyWith(
          productLists: state.productLists
              .map(
               ...etc
                ),
              )
              .toList(),
        ),
      );
```

2. Call a mutation to request update on the server

```
shelvesRepo.addProductToShelf().mutate(
            ShelfProductPatchModel(
              ...etc
            ),
          );
```

3. The addProductToShelf() mutation invalidates the query of the GET request which is providing the data to the UI via `Query<type>` as usual.

```
return Mutation<void, ShelfProductPatchModel>(
      refetchQueries: [_shelvesKey],
...etc
```

I am expecting to have this GET request stream update once and only once - when the API call returns with the updated data.

However, I seem to be getting two broadcasts into the stream, where the first broadcast is of the old (pre mutation) data, and the second is the updated (post mutation data).

So I am getting the following action.

1. UI updates optimistically on emit of new state.
2. UI receives data via stream. This is the pre-mutation data. The UI flickers back to original.
3. UI receives data via stream. This is the post mutation data. The UI flickers forward to again to match the optimistic update.

I can't use `onStartMutation` in this case because the args to the mutation are not enough for me to fully form the optimistic data models.

Are you able to shed any light on this? Should refetchQueries result in two broadcasts into the stream or is something going wrong here?

Thanks!

Rich

**Comment by D-James-GH** [comment]
Hi Rich, 
If I understand the problem properly, this is working as expected. When a query fetches it emits different states at different times in the life cycle. The first will be the loading state, which holds any existing data, then the success state, which will have the new data. 
What I am assuming you are doing is emitting a new state directly from the bloc event before you call "mutate". The data in the "shelves" query is never updated and presumably is still listened to by the bloc; so when the loading state comes through it will update the UI with old data. 

Fixing:
The easiest way to fix is to update the query data before you mutate. You don't need to use `onStartMutation`, that call back isn't doing anything special it is just called before the mutation happens. So what you can do is just update the `shelves` query manually instead of emitting from the block. 

Replace step 1 with the following: 
```dart
CachedQuery.instance.updateQuery(
  key: _shelvesKey,
  updateFn: (dynamic old) {
     // update the old data here
  },
);
```
This will trigger the "GET shelves" query to update its data and therefore update the UI optimistically. You will still see two stream broadcasts when refetching but the old data will now be the optimistically updated data.

**Comment by richisarch** [comment]
Hi,

Thanks for the super fast reply. That all makes sense now and I'm glad I'm not going mad with the double broadcasts :)

The above process works perfectly!! I guess I could also check the status of the query in the bloc's `emit.forEach()` listener and act accordingly (i.e assume that data is old when in this state)?

Thanks again!

Rich

**Comment by D-James-GH** [comment]
yeah, that would also work but might remove some of the benefits of cached query. It is usually best to treat the query as the source of truth for the api data.

**Comment by richisarch** [comment]
That's true, and directly updating the query data works great within the flutter_bloc architecture as you described.

Thanks
