### ISSUE TITLE
Question. Dependant queries

### ISSUE THREAD

**Issue by LiniovasDovydas** [D-James-GH/cached_query#3]
Coming from react-query background, for example I've created a query that depends on another query result, should I use stream inside the `Query<...> getSomething() { ... }` or it should come through for example function arguments ?

**Comment by D-James-GH** [comment]
Hi, I am not 100% what you are trying to do, however, there are are a couple of ways a query could depend on another query. Bear in mind that if you change the parameters to a request you should create a new query object with a different key. Similar to react-query where you need to change the query key. This is why it is easier to wrap a query in a function. eg 
```
Query<PostModel> getPostById(int id) {
  return Query<PostModel>(
    key: id,
    queryFn: () async {
      // fetch data
    },
  );
}
``` 
In the above code a new query will be created every time the id changes. 

The simplest way for a query to depend on another query would just be to await the result then use that result in another query.

```
final postResult = await getPostById(12).result;

callAnotherQueryWithPost( postResult.data );
```

You could also add a listener to the query stream and call the send query inside there. Although be careful with this as the stream will fire a lot (ie, loading, failed, etc).

A third option, if the queryFn's will alway depend on each other, might be to just combine them into one queryFn. 
```
Query<PostModel> getPostById(int id) {
  return Query<PostModel>(
    key: id,
    queryFn: () async {
      // fetch data from source 1
     // fetch data from source 2
    },
  );
}
``` 

Let me know if you have any other questions.

**Comment by LiniovasDovydas** [comment]
Thanks for the response, what I want to do is like make one combined query from two queries. 

Example in react
```
function useBranches() {
   const { data: permissions } = usePermissions(); // some other custom query
   const { data: branches } = useQuery(...); // <- new query

  return branches?.filter((branch) => permissions.branchesIds.includes(branch.id));
}
```

Basically reusable query (so if permissions or branches) refetch it filters the list again. But it's still a custom query.

As I image right now I'd need to do it like `QueryBuilder permissions -> QueryBuilder branches -> render the list` or am I missing something ? I want to keep combined queries out of widget if possible

**Comment by D-James-GH** [comment]
Thank you for clarification. In react you can utilise useState in any hook to trigger a re-render in the component, this is unfortunately less flexible in flutter, which is why builders are often utilised. You are correct, you would have to nest multiple builders inside each other to make sure both cause a re-render. However, I think for your situation there are a couple of alternatives.  
You could merge both queries into one queryFn. Below I am just guessing data, but something similar could work. It will cache the returned value. However, this approach means you can't use each query separately without creating different queries.
```
Query<BranchState> getBranches(int someInput) {
  return Query<BranchModel>(
    key: somInput,
    queryFn: () async {
      final permissionResult = await fetchPermissions(someInput);
      final branches = await fetchBranches(permissionResult);
      return branches?.where((branch) => permissions.branchesIds.any((branch) => branch.id));
    },
  );
}
```

Another option is to utilise RxDart and StreamBuilder to combine the two query streams into one. Using Rx.combineLatest2 should work. https://pub.dev/documentation/rxdart/latest/rx/Rx/combineLatest2.html
```
// Outside widget
final combinedQuery = Rx.combineLatest2(
  permissionQuery.stream,
  branchStream,
  (permissions, branches) => branches?.where((branch) => permissions.branchesIds.any((branch) => branch.id)));

// In widget
StreamBuilder(
  stream: combinedQuery, 
  builder: (snapshot) {
    // build UI
  }
)
```

Or you could utilise a state management library like flutter_bloc and combine the queries into a single bloc state.

**Comment by LiniovasDovydas** [comment]
Thanks! For now I'll go with creating nested QueryBuilder within the same file where the query. But the stream approach sounds interesting and may be something I'll try.
