### ISSUE TITLE
Question: Dynamic Queries

### ISSUE THREAD

**Issue by xeinebiu** [D-James-GH/cached_query#40]
Hi,

I have a question regarding the management of dynamically created queries. The documentation notes that when a `Query()` instance is created, it registers itself with `CachedQuery.instance`.

For example, the documentation shows something like this:

```dart
final query = Query<MyData>(
  key: 'someUniqueKey',
  queryFn: () async {
    // Query logic here
  },
);
```

This query is automatically registered with `CachedQuery.instance` for caching and lifecycle management.

My question is: how does this behavior apply to queries that are created dynamically during runtime? For instance, if I create a query dynamically within a function and use a unique key for it, as shown below:

```dart
Query<MyData> createDynamicQuery() {
  final dynamicKey = 'dynamicKey_${DateTime.now().millisecondsSinceEpoch}';
  return Query<MyData>(
    key: dynamicKey,
    queryFn: () async {
      // Your dynamic query logic here
    },
  );
}
```

Are these dynamically created queries supported by the library? What is the expected disposal behavior for such queries? Do they automatically dispose under certain conditions, or is there a need for manual intervention to manage their lifecycle?

**Comment by D-James-GH** [comment]
Hello, 
> how does this behavior apply to queries that are created dynamically during runtime?
A query is registered in the cache when the class is initialized which is at runtime. A Query is seen as unique if it has a a unique key. The factory that creates a query checks the cache for that key, if no query exists then one will be created, if there is a query already that one will be fetched from the cache. 

It is encouraged to use a dynamic query key that makes sense, eg. using the params of the request 
```dart
final dynamicKey = 'dyanmicKey_user=${id}'
```
In the above key a new query will be created for each user id. 

The dynamic key you are using in your example will create a new query every function call (because the time will change each call) so you will not be getting any benifits of a cached result. Therefore I would not recommend this. 

Query disposal is handled automatically and happens when the following two conditions are met:
1. There are no more listeners attached to the query.
2. The time since the last listener has been removed is greater than the `cacheDuration` (which can be set with options)

**Comment by xeinebiu** [comment]
> Hello,
> 
> > how does this behavior apply to queries that are created dynamically during runtime?
> > A query is registered in the cache when the class is initialized which is at runtime. A Query is seen as unique if it has a a unique key. The factory that creates a query checks the cache for that key, if no query exists then one will be created, if there is a query already that one will be fetched from the cache.
> 
> It is encouraged to use a dynamic query key that makes sense, eg. using the params of the request
> 
> ```dart
> final dynamicKey = 'dyanmicKey_user=${id}'
> ```
> 
> In the above key a new query will be created for each user id.
> 
> The dynamic key you are using in your example will create a new query every function call (because the time will change each call) so you will not be getting any benifits of a cached result. Therefore I would not recommend this.
> 
> Query disposal is handled automatically and happens when the following two conditions are met:
> 
>     1. There are no more listeners attached to the query.
> 
>     2. The time since the last listener has been removed is greater than the `cacheDuration` (which can be set with options)

Thank you for the clear explanation.

I have a quick question: If a query is created in different places with the same key, does the factory return the same instance, or is a new one created each time?

For example: Query<User> getUserById(id);

**Comment by D-James-GH** [comment]
You can call this: 
```dart
Query<MyData>(
    key: dynamicKey,
    queryFn: () async {
      // Your dynamic query logic here
    },
  )
```
Where ever you like and as many times as you like it will (nearly)always return the same instance. The only time it would return a different/new instance is if there is no query already in cache with that specific key. There might not be a query in cache if it has never been created OR it has been disposed of.

Below is the implementation of the factory: 
```dart
  /// {@macro query}
  factory Query({
    required Object key,
    required Future<T> Function() queryFn,
    OnQueryErrorCallback<T>? onError,
    OnQuerySuccessCallback<T>? onSuccess,
    T? initialData,
    QueryConfig? config,
  }) {
    final globalCache = CachedQuery.instance;
    var query = globalCache.getQuery(key) as Query<T>?;

    // if query is null check the storage
    if (query == null) {
      query = Query<T>._internal(
        key: encodeKey(key),
        unencodedKey: key,
        queryFn: queryFn,
        onError: onError,
        onSuccess: onSuccess,
        initialData: initialData,
        config: config,
      );
      globalCache.addQuery(query);
    }

    return query;
  }

```

**Comment by xeinebiu** [comment]
> You can call this:
> 
> ```dart
> Query<MyData>(
>     key: dynamicKey,
>     queryFn: () async {
>       // Your dynamic query logic here
>     },
>   )
> ```
> 
> Where ever you like and as many times as you like it will (nearly)always return the same instance. The only time it would return a different/new instance is if there is no query already in cache with that specific key. There might not be a query in cache if it has never been created OR it has been disposed of.
> 
> Below is the implementation of the factory:
> 
> ```dart
>   /// {@macro query}
>   factory Query({
>     required Object key,
>     required Future<T> Function() queryFn,
>     OnQueryErrorCallback<T>? onError,
>     OnQuerySuccessCallback<T>? onSuccess,
>     T? initialData,
>     QueryConfig? config,
>   }) {
>     final globalCache = CachedQuery.instance;
>     var query = globalCache.getQuery(key) as Query<T>?;
> 
>     // if query is null check the storage
>     if (query == null) {
>       query = Query<T>._internal(
>         key: encodeKey(key),
>         unencodedKey: key,
>         queryFn: queryFn,
>         onError: onError,
>         onSuccess: onSuccess,
>         initialData: initialData,
>         config: config,
>       );
>       globalCache.addQuery(query);
>     }
> 
>     return query;
>   }
> ```

Thanks for taking your time to assist on this matter.

I think we have a little bit of missunderstanding here. Let me add more context on my example

```dart
Query<User> getUserById(String userId) {
  return Query<User>(
     key: "get_user_by_id_" + userId,
    ...
  ):

}
````

On the above code, we are creating a Query object (calling the factory at least) dynamically with different keys for different users. 

Now the question is if this is supported and recommended. Different parts of the application might call `getUserById` with the same `userId`. Is it the same `Query` going to be reused?

Thanks in advance.

**Comment by D-James-GH** [comment]
Yes, that's correct. If you call your function with the same userid the query will be reused because the resulting key ("get_user_by_id_123") will be the same. A new query will only created if you call `getUserById` with a new/different `userId`. The old query will also still be available in cache until it is disposed, all Query's will be cached separately under the different keys. 

```dart
final user1 = getUserById("1234");
final user2 = getUserById("1234");
final user3 = getUserById("4567");
assert(user1 == user2);
assert(user1 != user2);
```

In the above example variables `user1` and `user2` are the same instance of a query. `user3` is a completely different query. So you can call `getUserById("1234")` anywhere in your application without passing around the user1 variable.

**Comment by xeinebiu** [comment]
> Yes, that's correct. If you call your function with the same userid the query will be reused because the resulting key ("get_user_by_id_123") will be the same. A new query will only created if you call `getUserById` with a new/different `userId`. The old query will also still be available in cache until it is disposed, all Query's will be cached separately under the different keys.
> 
> ```dart
> final user1 = getUserById("1234");
> final user2 = getUserById("1234");
> final user3 = getUserById("4567");
> assert(user1 == user2);
> assert(user1 != user2);
> ```
> 
> In the above example variables `user1` and `user2` are the same instance of a query. `user3` is a completely different query. So you can call `getUserById("1234")` anywhere in your application without passing around the user1 variable.

Thank you very much for the clearification. This makes the behavior of Query similar to ReactQuery has, which is something I needed.

Closing the Issue.

**Comment by JJosephttg** [comment]
The problem with creating the query is that it seems like the behavior subject that is created here:

https://github.com/D-James-GH/cached_query/blob/main/packages/cached_query/lib/src/query/query.dart#L145C5-L145C44

does not respect listeners of the stream. If we are creating on new query keys being changed, we also are forced to resubscribe to the stream since the old behavior subjects are no longer active. Seems like the controller should be the one defining the stream and not the query class itself
