### ISSUE TITLE
Internal use of dynamic?

### ISSUE THREAD

**Issue by clragon** [D-James-GH/cached_query#51]
**Preamble**
I am interested in using this package because it fulfills a very important usecase which I am interested in;
React Query-like caching but without being UI-bound by default (dart only). This is great for having strong API data caching at the controller level.
For that reason I was reading the source code.

**Discussion**
I am curious to understand why the package uses `dynamic` predominantly internally.
This doesn't pose a direct problem to users of the package. Most types which are `dynamic` are shielded by an actual concrete type before being exposed.
However, this poses the question: Why are these types `dynamic` at all?

For example, looking at `StateBase`, we can see:

```dart
abstract class StateBase {
  /// Current data of the query.
  dynamic get data;
```

`StateBase` uses `dynamic` for its `data` getter. The only usage of `StateBase` is `QueryState<T>` which immediately overrides this with:

```dart
class QueryState<T> implements StateBase {
  /// Current data of the query.
  @override
  final T? data;
```

making it strongly typed.
I have checked all other extension packages but none ever reference `StateBase` directly. 
The type is exported publicly, but does not seem to be used anywhere.

Another example of a `dynamic` type which does not immediately seem justified to me is found in the `Query<T>` class:

```dart
class Query<T> extends QueryBase<T, QueryState<T>> {
  final Function _queryFn;
```

The internal query function of the `Query<T>` class is not typed `Future<T> Function()` as one might expect, but rather a function with a dynamic return type and dynamic parameters. 

Externally, the function is strongly typed:

```dart
  factory Query({
    required Object key,
    required Future<T> Function() queryFn,
```

and in the `_fetch` function, we can see that to regain type safety, the code asserts the type:

```dart
final res = await (_queryFn() as Future<T>);
```

Inspecting the code, I was unable to find any reason as to why this function would be stored like this, as opposed to being strongly typed itself. It is never invoked nor set in a manner that would explain this. 

One more notable place where dynamic is used is the `InfiniteQueryState<T>` class. 
Despite `InfiniteQuery<T, Arg>` having a generic type for its keys, this type is not passed down to the corresponding state class:

```dart
class InfiniteQuery<T, Arg> extends QueryBase<List<T>, InfiniteQueryState<T>> {
```

which leads to:

```dart
class InfiniteQueryState<T> extends QueryState<List<T>> {
  final dynamic Function(InfiniteQueryState<T>) _getNextArg;
```

Lastly, `QueryBase<T, State extends QueryState<dynamic>>` uses `dynamic` directly for its `QueryState<dynamic>`, despite `T` being known. The `State` getter that it exposes:

```dart
  /// The current state of the query.
  State get state => _state;
```

could be fully typed, instead of being a subtype of `QueryState<dynamic>`. 

**Closing**
I would love to hear your thoughts on this. I would feel greatly bolstered in choosing this library if assured that it has strong typing, not just externally but also internally.

**Comment by D-James-GH** [comment]
sure, I'll go through these 1 by 1. However, please note I am planning/implementing a lot of internal code refactors for 3.0.0 so many of these will be changing. 

> abstract class StateBase {
  /// Current data of the query.
  dynamic get data;

This is only used as an interface. This is an interface only. This was originally the interface for both querystate and infinitequerystate. This will be refactored when implementing https://github.com/D-James-GH/cached_query/issues/48.

>class Query<T> extends QueryBase<T, QueryState<T>> {
  final Function _queryFn;

You are correct with this one, this is not necessary and will be updated. However, the external interface is correct so the dynamic here does not effect the running of the code.

>class InfiniteQueryState<T> extends QueryState<List<T>> {
  final dynamic Function(InfiniteQueryState<T>) _getNextArg;
   
This one is intentional. InfiniteQueryState is used as a type parameter in a few places externally (eg in the querybuilders). Adding the arg type parameter provides no benefit to the user and just requires more typing. The return type of `_getNextArg(this)` inside of `InfiniteQueryState` makes no difference. The only thing it is used for is to check if the infinite query `hasReachedMax` (by checking if the runtime value is null or not). There is no benefit to knowing the type of the return type at compile time (ONLY inside the state object). Where the return type of this function matters is inside the `InfiniteQuery` object, inside this object the `getNextArg` is typed fully. 

>   /// The current state of the query.
  State get state => _state;

This is an interface which narrows the type parameter  to any class that extends `QueryState`. This is statically typed properly because the actual type that is passed to the QueryBase is the one that the user specifies when creating a Query or InfiniteQuery. Admittedly, it could be changed to T, however, as it's just a type narrower it wouldn't make any difference to the code inside QueryBase

**Comment by clragon** [comment]
I see. So from what I understand, all of these instances of dynamic could be correctly typed.

To me personally, dynamic is both like a linter warning and a flash bang. 
If I read dynamic, this means something has most likely gone wrong. The dart language has an incredible advantage with sound typing, making users fully aware of what types theyre working with at all times and preventing errors at compile time. 

I believe the only instance where dynamic is the correct choice is if it is close to inevitable. One example is JSON deserialisation, where we simply cannot correctly type the result ahead of time. This is a limit of the language. 
Generally, I think this is a sentiment that many people in the dart community share.

As I have mentioned initially and as you have reiterated, these types usually dont touch the users of the package. Nonetheless I think it not hurt to replace dynamic with strong types. It is an easy practice to ensure everything is what we expect it to be, even when it "doesn't matter".

**Comment by D-James-GH** [comment]
I agree with you to a certain extent. However, I believe dynamic is a useful type for a lower level interfaces and allows type narrowing to be done by the implementor of the interface. `StateBase` for example is an interface and is never directly used. Adding a static type here through type parameters adds no benefit and only increases the amount code needed to be written. There is no logic based off the fact that it is dynamic. Implementors then add a type to this data property so for all uses of the data property it is fully typed. 

The only one you stated that I feel is in need of a change is 
```dart
class Query<T> extends QueryBase<T, QueryState<T>> {
  final Function _queryFn;
```
As this is part of the implementation and has been incorrectly typed.

You are right, the others can be changed as well, and I am happy to do that, however, the only one I would not change is the `final dynamic Function(InfiniteQueryState) _getNextArg;` inside `InfiniteQueryState` as adding the return type as a argument would not add any benefits and be a detriment to the user of the package.

**Comment by clragon** [comment]
I am glad you agree. 
However, I do not quite understand why `_getNextArg` being typed would be a detriment to the user. 
How would this force the user to ever declare additional types, and why do you suppose they would not be happy to do so?
Personally I would be glad if the return type of a function is enforced correctly so I can be sure that I did not accidentially return the wrong thing inside of it.

**Comment by D-James-GH** [comment]
Implemented most of these. There will be an internal refactor of a few things in version 3 so I will pay attention to any typing improvements that can be made.
