### ISSUE TITLE
Question. Dependant queries 2

### ISSUE THREAD

**Issue by MichaelM-ZGuy** [D-James-GH/cached_query#57]
There's already been a [question asked](https://github.com/D-James-GH/cached_query/issues/3) about dependent queries (coming from a `react-query` background), but it didn't quite match my particular case.

As we know, a query will fire as soon as it is created. However, what if we only want the query to fire in certain cases? `react-query`, for example, has an `enabled` argument:

```
// https://tanstack.com/query/latest/docs/framework/react/guides/dependent-queries#usequery-dependent-query
const {
  status,
  fetchStatus,
  data: projects,
} = useQuery({
  queryKey: ['projects', userId],
  queryFn: getProjectsByUser,
  // The query will not execute until the userId exists
  enabled: !!userId,
})
```

In my particular case, I need the query to fire only for certain user roles. If `cached_query` had an `enabled` argument, I'd do something like this:

```
query = Query<List<ChatModel>>(
      key: queryKey,
      queryFn: _api.getChats,
      enabled: user != null && !user.isAdmin
    );
```

How can we conditionally execute a query in `cached_query`?

**Comment by D-James-GH** [comment]
Hey @MichaelM-ZGuy ,
In Cached Query, the querys are only fetched if you call `Query.result` or listen to the stream `Query.stream`. 
In your example: 
```dart
// The queryFn below will not be called
query = Query<List<ChatModel>>(
      key: queryKey,
      queryFn: _api.getChats,
      enabled: user != null && !user.isAdmin
    );

// This calls the queryFn
await query.result 
```

When you pass a query to a `QueryBuilder` the queryFn is called. This is because the `QueryBuilder` automatically listens to the stream (which in turn calls the queryFn). 
The `QueryBuilder` does have an `enabled` flag to combat this. 

So to answer your question; If you don't want the `queryFn` to be called until certain user roles are met then your would either: 
1. Wrap the stream subscription/result future in a conditional based on user roles
2. use the enabled flag on a `QueryBuilder` 

Hope that helps, let me know if you have any other questions.

**Comment by MichaelM-ZGuy** [comment]
> In Cached Query, the querys are only fetched if you call Query.result or listen to the stream Query.stream.
Ah, righto, thanks for clearing that up. I found a way to make it work.
